name: test223
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo test-${{inputs.username}}