name: 'Local Action'
description: 'Local action inside reusable workflow testing'
# runs:
#   using: node12
#   main: index.js

runs:
  using: composite
  # default:
  run:
    shell: sh
  steps:
    - run: echo 999