name: 'Local Action'
description: 'Local action inside reusable workflow testing'
outputs:
  outputVar1:
    value: ${{steps.step22.outputs.outputVar}}
# runs:
#   using: node12
#   main: index.js
# shell: sh
runs:
  using: composite
  runs-on: ubuntu-18.04
  steps:
    - id: step22
      run: echo "::set-output name=outputVar::test-output"