name: 'Local Action'
description: 'Local action inside reusable workflow testing'
# runs:
#   using: node12
#   main: index.js
# shell: sh
runs:
  using: composite
  steps:
    - id: step22
      run: echo 999
      shell: sh