name: test workflow_call call
on:
  workflow_call:
    inputs:
      test:
        default: 100f
        type: string
jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - run: echo ttt6${{inputs.test}}