on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "new content" > test/t1.js
      - run: ls test
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact2
          path: test
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact2
      - run: ls test