on: push
jobs:
  login-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWD}}
      - uses: docker/setup-buildx-action@v1
      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./build/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-github-actions:latest
      - run: echo ${{ steps.docker_build.outputs.digest }}