on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir tes2
          echo "new content" > tes2/t1.js
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact2
          path: tes2
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact2
      - run: ls tes2