name: test push when call
on:
  push
jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - run: echo job1.step1.output
      - run: echo "::set-output name=step2Output::job1_step2_output"
  job2:
    runs-on: ubuntu-18.04
    steps:
      - run: echo ${{jobs.job2.outputs.step2Output}}
      - run: echo job2.step1.output
