on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12, 14, 16]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: node -v