name: test node start
on:
  push:
    branches:
      - master
jobs:
  job1:
    name: echo-100
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: job1-step-2
      run: |
        ls -a
        echo 1909
