name: dispatch-test
on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'fsf'
        required: true
        type: string
jobs:
  job1:
    run-on: ubuntu-latest
    steps:
      - run: echo ${{inputs.input1}}-test