name: test push when call
on:
  push
jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/myaction
        with:
          testName: test 66 gg
      - run: echo test2
