on: push
jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-primes
  docker-hub2:
    runs-on: ubuntu-latest
    needs: docker-hub
    steps:
      - uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-primes
      - run: ls