on: push
jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWD}}
      - id: getDateTime
        name: get-date-str
        run: echo "::set-output name=dateStr::$(date +'%Y%m%d%H%M%S')"
      - id: docker_build
        name: build-image
        uses: docker/build-push-action@v2
        with:
          context: ./build/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-github-actions:${{steps.getDateTime.outputs.dateStr}}
      - run: echo ${{ steps.docker_build.outputs.digest }}