name: test workflow_dispatch-copy
on:
  workflow_run:
    workflows: test_workflow_dispatch
    types: completed
jobs:
  job2:
    name: echo-10023
    runs-on: ubuntu-18.04
    steps:
      - run: echo 1000
