name: test workflow_dispatch
on:
  workflow_dispatch:
jobs:
  job1:
    name: echo-100
    runs-on: ubuntu-18.04
    steps:
      - run: echo ::set-output name=docker_tag::test9909-${GITHUB_SHA}
        id: step1-1
  job2:
    name: echo-100
    runs-on: ubuntu-18.04
    steps:
      - run: echo ${{steps.step1-1.outputs.docker_tag}}
