name: test workflow_dispatch
on: push
jobs:
  job2:
    name: echo-1002
    runs-on: ubuntu-18.04
    steps:
      - uses: keepsaunter/test-github-actions/.github/workflows/test_workflow_call.yml@main
        with:
          username: oc
      - run: echo 90
