name: test workflow_dispatch
on: push
jobs:
  uses: keepsaunter/test-github-actions/.github/workflows/test_workflow_call.yml@master
  job2:
    name: echo-10021
    runs-on: ubuntu-18.04
    steps:
      - run: echo 90
