name: test workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  job1:
    name: echo-100
    runs-on: ubuntu-18.04
    steps:
    - run: echo ${{inputs.tags}}workflow_dispatch
