name: test workflow_dispatch
on: push
jobs:
  job2:
    name: echo-1002
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: ls -a /home/runner/work/test-github-actions/test-github-actions/.github/workflows
      - uses: ./test_workflow_call.yaml
        with:
          username: oc
      - run: echo 90
