name: test workflow_dispatch
on: push
jobs:
  job1:
    name: echo-1001
    runs-on: ubuntu-18.04
    steps:
      - id: step1-1
        run: echo "::set-output name=docker_tag::test9909-${GITHUB_SHA}"
      - run: echo tt${{steps.step1-1.outputs.docker_tag}}
